version: '2'

services:
  # DNS Server
  dns:
    image: sniggel/cluster-sandbox-dns:latest
    ports:
    - "53/udp"
    - "953"
    networks:
      app_net:
        ipv4_address: 172.180.0.2

  # Cluster Host 1 - dc-montreal - host 1
  host1:
    image: sniggel/cluster-sandbox:latest
    ports:
      - "9000/tcp"
      - "8558/tcp"
      - "2552/tcp"
      - "9042/tcp"
    dns: 172.180.0.2
    environment:
      - JAVA_OPTS=-Dakka.cluster.multi-data-center.self-data-center=montreal -Dcassandra-journal.contact-points.0=172.180.0.7:9042 -Dcassandra-snapshot-store.contact-points.0=172.180.0.7:9042
    networks:
        app_net:
            ipv4_address: 172.180.0.3

  # Cluster Host 2 - dc-montreal - host 2
  host2:
    image: sniggel/cluster-sandbox:latest
    ports:
      - "9000/tcp"
      - "8558/tcp"
      - "2552/tcp"
      - "9042/tcp"
    dns: 172.180.0.2
    environment:
    - JAVA_OPTS=-Dakka.cluster.multi-data-center.self-data-center=montreal -Dcassandra-journal.contact-points.0=172.180.0.7:9042 -Dcassandra-snapshot-store.contact-points.0=172.180.0.7:9042
    networks:
      app_net:
        ipv4_address: 172.180.0.4

  # Cluster Host 3 - dc-quebec - host 1
  host3:
    image: sniggel/cluster-sandbox:latest
    ports:
      - "9000/tcp"
      - "8558/tcp"
      - "2552/tcp"
      - "9042/tcp"
    dns: 172.180.0.2
    environment:
    - JAVA_OPTS=-Dakka.cluster.multi-data-center.self-data-center=quebec -Dcassandra-journal.contact-points.0=172.180.0.8:9042 -Dcassandra-snapshot-store.contact-points.0=172.180.0.8:9042
    networks:
        app_net:
            ipv4_address: 172.180.0.5

  # Cluster Host 4 - dc-quebec - host 2
  host4:
    image: sniggel/cluster-sandbox:latest
    ports:
      - "9000/tcp"
      - "8558/tcp"
      - "2552/tcp"
      - "9042/tcp"
    dns: 172.180.0.2
    environment:
    - JAVA_OPTS=-Dakka.cluster.multi-data-center.self-data-center=quebec -Dcassandra-journal.contact-points.0=172.180.0.8:9042 -Dcassandra-snapshot-store.contact-points.0=172.180.0.8:9042
    networks:
      app_net:
        ipv4_address: 172.180.0.6

  # Cassandra server for dc-montreal
  cassandra-dc-montreal:
    image: cassandra:3.11.2
    ports:
    - "9042"
    networks:
      app_net:
        ipv4_address: 172.180.0.7

  # Cassandra server for dc-quebec
  cassandra-dc-quebec:
    image: cassandra:3.11.2
    ports:
    - "9042:9042"
    networks:
      app_net:
        ipv4_address: 172.180.0.8

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.180.0.0/24
        gateway: 172.180.0.1
