from openjdk:8-jre-alpine

WORKDIR /
COPY cluster-sandbox-assembly-0.1.0-SNAPSHOT.jar cluster-sandbox-assembly-0.1.0-SNAPSHOT.jar
EXPOSE 2552
EXPOSE 8558
CMD java -jar cluster-sandbox-assembly-0.1.0-SNAPSHOT.jar